defaultPortal: 'o[3~t:Joash'
portals:
  - name: 'o[3~t:Joash'
    portalId: 45350943
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKKzjc7eMRIRAAUAQAAAAGwAQAJYAgEAAAgYn4DQFSC4h9ceKO7pDDIUr3JSHI8eLseNn3tPbnupiWM_6pU6QQAABEEAAAAAAAAAAAAAAAAAgAAAAAAABAAAAAAAAAAAPGBQAABEAABA_BgGABAgAwAAAAAADAAAAAAAAAAAAAAEQhQgQwoSeI8k-upHeEgbaooiB5WKsEoDbmExUgBaAA
        expiresAt: '2024-02-27T08:51:50.333Z'
    personalAccessKey: >-
      CiRkY2MzZjZiZi0zNmEzLTRlNDEtYmU3Yy1iOTdiMzA1NTM0MjAQn4DQFRi4h9ceKhkABeaRggcPEkVRpQzjjc8U9Lb72IQPOYiASgNuYTE
